#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V
# bspc monitor HDMI-1-0 -d A B C D E

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a ArmCord desktop='^2'
bspc rule -a Beeper destop='^2'
bspc rule -a firefox:Toolkit state=floating sticky=on
bspc rule -a dunst focus=off
bspc rule -a polkit-ukui-authentication-agent-1 state=floating 
bspc rule -a PrimeNote state=floating 
bspc rule -a polybar state=floating sticky=on
bspc rule -a steam:steamwebhelper state=hidden

# dex -a
touch /tmp/historylist
bolt --generate
picom -b
polybar mainbar -r &
polybar offbar -r &
feh --bg-scale /home/maxine/Documents/Pictures/Firefox_wallpaper.png &
touchegg &
flameshot &
clipmenud &
primenote &
bash /home/maxine/.config/bspwm/bspwm_colors.sh &
/home/maxine/Software/ArmCord*.AppImage &
/home/maxine/Software/beeper*.AppImage &
/home/maxine/Software/hideIt.sh -N "^offbar\$" -d bottom -w -r 1420x2400+1000+-80 -s 6 -i 0.1 -p 8
