#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V
# bspc monitor HDMI-1-0 -d A B C D E

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a armcord desktop='^2'
bspc rule -a beeper destop='^2'
bspc rule -a firefox:Toolkit state=floating sticky=on
bspc rule -a dunst focus=off
bspc rule -a polkit-ukui-authentication-agent-1 state=floating 
bspc rule -a PrimeNote state=floating 

picom --experimental-backends &
polybar mainbar --config=./.config/polybar/config.ini -r &
feh --bg-scale /home/maxine/Documents/Pictures/Firefox_wallpaper.png &
touchegg &
flameshot &
clipmenud &
bash /home/maxine/.config/bspwm/bspwm_colors.sh &
# screen -S httpserver http-server Documents/Neocities/ &
./home/maxine/Software/ArmCord-3.1.4_89d476e8bebc68418c2f53a1d53ed7f4.AppImage &
firefox &
