# vim: ft=cfg
# Basic options
default_keybindings = false
use_nerdfont = true
notify = true
gapless = true
flip_status_indicators=true
shuffle = true
repeat = 'playlist'
playback_state = "Playing"
library_tabs = [ "playlists", "artists", "tracks", "browse" ]

[keybindings]
## unbinded: nN, c, eE, xX
######################################
# Song controls
######################################

##################
# Fast forward / rewind
##################
"b" = "seek -1000"
"f" = "seek +1000"
"Shift+b" = "seek -10000"
"Shift+f" = "seek +10000"

##################
# Play / pause
##################
"p" = "playpause"
"Enter" = "play"
"t" = "stop"

##################
# Track manipulation
##################
"Shift+n" = "previous"
"n" = "next"
"<" = "previous"
">" = "next"

"r" = "repeat"
"s" = "shuffle"

"Shift+d" = "delete"
"Shift+s" = "save"

# Open context menu
"Shift+a" = "goto artist"
"a" = "goto album"

##################
# Queue
##################
# Add to queue
"z" = "queue"
"Ctrl+s" = "save queue"
# Move selected song up/down in the queue
"Shift+j" = "shift down 1"
"Shift+k" = "shift up 1"
"Shift+c" = "clear"
# Open the context menu for a Spotify link in the clipboard
"Ctrl+v" = "insert"

######################################
# Sound
######################################
"=" = "volup 1"
"-" = "voldown 1"
"]" = "volup 5"
"[" = "voldown 5"


######################################
# Movements
######################################
"1" = "focus library"
"2" = "focus queue"
"3" = "focus cover"
"shift+s" = "focus search"
"shift+z" = "focus queue"

# Navigation
"Backspace" = "back"

"Shift+g" = "move bottom"
"g" = "move top"

"j" = "move down 1"
"k" = "move up 1"
"Tab" = "move right 1"
"Shift+Tab" = "move left 1"

"h" = "back"
"l" = "open selected"
"o" = "open current"
"." = "move playing"
"q" = "quit"

######################################
# Sorting
######################################
"w" = "sort added d"
"Shift+t" = "sort title a"

######################################
# Sharing
######################################
"Shift+y" = "share selected"
"y" = "share current"

######################################
# Other
######################################
"?" = "help"
"Shift+u" = "update"
"Shift+r" = "reload"


# Gruvbox dark [ originally based on base16 by Dawid Kurek (dawikur@gmail.com) ]
[theme]
background = "default"
primary = "#ebdbb2"
secondary = "#928374"
title = "#8ec07c"
playing = "#689d6a"
playing_bg = "#383838"
playing_selected = "#ebdbb2"
highlight = "#d5c4a1"
highlight_bg = "#484848"
error = "#fbf1c7"
error_bg = "#cc241d"
statusbar_progress = "#458588"
statusbar_bg = "#282828"
statusbar = "#98971a"
cmdline = "#d5c4a1"
cmdline_bg = "#383838"
search_match = "#fabd2f"
