# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks-git.nvim" = "2.0.1"
"rocks-treesitter.nvim" = "scm"
"venn.nvim" = "scm"
"gruvbox.nvim" = "2.0.0"
neorg = "9.1.1"
nvim-autopairs = "scm"
"mini.nvim" = "0.9.0"
"mini.files" = "0.13.0"
"mini.animate" = "0.9.0"
"mini.comment" = "0.9.0"
"mini.move" = "0.9.0"
luasnip = { git = "L3MON4D3/LuaSnip", build = "make install_jsregexp", opt = true}
"lspkind.nvim" = { git = "onsails/lspkind.nvim",  opt = true}
"conform.nvim" = "6.1.0"
nvim-lspconfig = "0.1.8"
"dressing.nvim" = "2.2.2"
"sqlite.lua" = "1.2.2"
"nabla.nvim" = "scm"
nvim-cokeline =  "0.4.0"
nvim-treesitter = { git = "nvim-treesitter/nvim-treesitter", rev = "v0.9.2^{}" }
nvim-surround = { version = "2.1.5", config = true }
"mason.nvim" = { version = "1.10.0", opt = true, config = true }
cmp_luasnip = "scm"
tree-sitter-xml = "scm"
cmp-buffer = "scm"
"hover.nvim" = "scm"
"image.nvim" = "1.3.0"
"nui.nvim" = "0.3.0"
"noice.nvim" = "4.4.5"
"repeat.vim" = "1.2"
tree-sitter-toml = "scm"
tree-sitter-yaml = "scm"
tree-sitter-ini = "scm"
tree-sitter-zig = "scm"
tree-sitter-json = "scm"
tree-sitter-css = "scm"
tree-sitter-readline = "scm"
tree-sitter-sxhkdrc = "scm"
tree-sitter-tmux = "scm"
"lazygit.nvim" = "scm"

[plugins.nvim-cmp ]
git = "hrsh7th/nvim-cmp"
rev = "d818fd0624205b34e14888358037fb6f5dc51234"

[plugins."rocks-config.nvim" ]
version = "1.6.0"
pin = true

[plugins."rocks.nvim" ]
version = "2.24.0"
pin = true

[plugins."lspsaga.nvim"]
version = "scm"
# config.use_diagnostic_virtual_text = false

[plugins.nvim-notify]
version = "3.13.5"
config.background_colour = "#282828"
config.fps = 60
config.stages = "slide"
config.minimum_width = 0
config.max_width = 60

[plugins."marks.nvim" ]
version = "scm"
# config = true

[plugins.cmp-nvim-lsp ]
git = "hrsh7th/cmp-nvim-lsp"

[plugins."mason-lspconfig.nvim"]
version = "1.29.0"
opt = true
config.ensure_installed = ["lua_ls", "clangd", "bashls", "cssls", "diagnosticls", "html", "jdtls", "jsonls", "quick_lint_js", "ltex", "marksman", "pyright"]

[plugins."pretty-fold.nvim"]
git = "bbjornstad/pretty-fold.nvim"
config.fill_char = " "
config.keep_indent = false
config.sections.left = ["", "content", " ", "number_of_folded_lines"]
config.sections.right = ["percentage", " "]

[plugins."which-key.nvim"]
version = "3.12.0"

[plugins.nvim-neoclip]
name = "nvim-neoclip"
git = "AckslD/nvim-neoclip.lua"
config.default_register = '*'
config.enable_persistent_history = true
config.continuous_sync = true
config.content_spec_column = true
config.keys.telescope.i.paste = "<CR>"

[plugins."lualine.nvim"]
version = "scm"
config.icons_enabled = true
config.theme = "auto"

[plugins."telescope.nvim"]
version = "scm"
config.defaults.layout_config.vertical = { width = 0.9, preview_height = 0.3 }
config.defaults.layout_strategy = "vertical"

[plugins.cmp-async-path]
git = "FelipeLema/cmp-async-path"

[plugins."zig.vim"]
git = "ziglang/zig.vim"

[plugins.cmp-latex-symbols]
git = "kdheepak/cmp-latex-symbols"

[plugins."eagle.nvim"]
git = "soulis-1256/eagle.nvim"
opt = true

[plugins."wrapping.nvim"]
git = "andrewferrier/wrapping.nvim"
rev = "v1.2.0"
config = true

[plugins."leap.nvim"]
git = "ggandor/leap.nvim"

[plugins."hovercraft.nvim"]
git = "patrickpichler/hovercraft.nvim"

[plugins.pretty_hover]
git = "Fildo7525/pretty_hover"
rev = "v0.1.2"

[plugins."hoverdown.nvim"]
git = "mskelton/hoverdown.nvim"
config = {}

[plugins."cinnamon.nvim"]
git = "declancm/cinnamon.nvim"
config.keymaps.basic = true
rev = "v1.2.3"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"
config = {}

[plugins.nvim-dap]
git = "mfussenegger/nvim-dap"
rev = "0.8.0^{}"

[plugins.nvim-dap-ui]
git = "rcarriga/nvim-dap-ui"
rev = "v4.0.0"

[plugins.nvim-dap-virtual-text]
git = "thehamsta/nvim-dap-virtual-text"

[plugins.supermaven-nvim]
git = "supermaven-inc/supermaven-nvim"
config.disable_inline_completion = true

[plugins.cmp-cmdline]
git = "hrsh7th/cmp-cmdline"

[plugins.cmp-path]
git = "hrsh7th/cmp-path"

[config]
plugins_dir = "plugins/"
auto_setup = false

[treesitter]
auto_highlight = "all"
